✨ Added commands for German language.
Donshel/sleek-template pull request #5
Opened 2022-11-12 15:03 UTC by JanB1

Added some commands and definitions for the German language.

2022-11-16 16:17 UTC, francois-rozet commented
Hello @JanB1, thank you for your contribution! I will review it shortly.

2022-11-16 16:23 UTC, francois-rozet requested changes
Looks good to me overall. I left two comments for you to fix, and we can merge afterwards!

2022-11-17 13:23 UTC, JanB1 commented
I implemented the requested changes.

2022-11-17 22:02 UTC, JanB1 commented on packages/sleek.sty
> +    backrefpages = {pages}
Yeah, didn't notice that one, good catch!

2022-11-18 12:29 UTC, merged

2022-11-18 13:42 UTC, francois-rozet commented
I just realized that the `babel` package already translates the captions and table of contents. So I dropped the related code in `sleek.sty` but kept the translations in `sleek-theorems.sty`. Thanks again for the contribution and sorry for the little mess 😅